In [ ]:
id = [i for i in range(1,17)]

age = [60, 61, 74, 57, 63, 68, 66, 77, 63, 54, 63, 76, 60, 61, 65, 79]

weight = [58, 90, 96, 72, 62, 79, 69, 96, 96, 54, 67, 99, 74, 73, 85, 80]

sbp= [117, 120, 145, 129, 132, 130, 110, 163, 136, 115, 118, 132, 111, 112, 0, 0]

from sklearn.linear_model import LinearRegression

import pandas as pd

data = {"age":age, "Weight":weight, "SBP":sbp}

data = pd.DataFrame(data = data)

x = data[["age", "Weight"]]

y = data["SBP"]

x_train = x[:14]

x_test = x[14:]

y_train = y[:14]

y_test = y[14:]

model = LinearRegression()

model.fit(x_train, y_train)

predict = model.predict(x_test)

print(predict)

[129.01956696 142.76293569]


In [34]:
def der_theta(t0, t1, lst):
  
  der_theta0_val, der_theta1_val = 0, 0
  
  for (x,y) in lst:
    der_theta0_val=der_theta0_val+((t0+t1*x)-y)
    der_theta1_val=der_theta1_val+(((t0+t1*x)-y)*x)
    
  return (der_theta0_val, der_theta1_val)

def theta_val(theta0_init,theta1_init,alpha,E,lst): # training set
  
  (der_t0,der_t1)=der_theta(theta0_init, theta1_init, lst)
 # Test
  theta0,theta1=theta0_init, theta1_init
  m=len(lst)		# Total number of (x,y) pairs

  while(abs(der_t0)>= E or abs(der_t1)>= E):
    theta0=theta0-alpha/m*der_t0;
    theta1=theta1-alpha/m*der_t1;
    # print('theta0=',theta0, 'theta1=',theta1,'der_t0=',der_t0, 'der_t1=',der_t1)  # Testing
    (der_t0,der_t1)=der_theta(theta0,theta1,lst) # Get new derivitive values

  return (theta0,theta1)

row_data=[[0,4],[1,5],[2,16],[3,21],[4,36],[5,45],[6,64],[7,77],[8,100],[9,117],[10,144]]

theta0_init,theta1_init=0.0, 0.0
alpha=0.01	# Set up the learning rate
E=0.0001	

def get_theta():
  return theta_val(theta0_init,theta1_init,alpha,E,row_data)


theta0,theta1 = get_theta()

print(theta0,theta1)


-12.818149416912124 13.999995333924602


In [ ]:
import numpy as np


X=[[1, 1],[1, 3],[1, 5],[1, 7],[1, 9],[1, 11],[1, 13],[1, 15],[1, 17],[1, 19,20-1]]

a = np.array([[1, 1],[1, 3],[1, 5],[1, 7],[1, 9],[1, 11],[1, 13],[1, 15],[1, 17],[1, 19]])

print(a)

print(a.shape)

a_trans=a.transpose()

print(a_trans)

a_trans.shape

print(a_trans.dot(a))

u=np.linalg.inv(a_trans.dot(a))

v=u.dot(a_trans)

v.shape

Y=np.array([[2+1],[4-1],[6+1],[8-1],[10+1],[12-1],[14+1],[16-1],[18+1],[20-1]])

Y.shape

print(v.dot(Y))


[[ 1  1]
 [ 1  3]
 [ 1  5]
 [ 1  7]
 [ 1  9]
 [ 1 11]
 [ 1 13]
 [ 1 15]
 [ 1 17]
 [ 1 19]]
(10, 2)
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  3  5  7  9 11 13 15 17 19]]
[[  10  100]
 [ 100 1330]]
[[1.3030303 ]
 [0.96969697]]
